triggers:
  - kind: apipushtrigger  # Keep the trigger type
    branch: master  # Keep the branch name (assuming "master" is correct)
    repo: harry976/LiquorPediaAPI  # Keep the repository details
    substitutions:
      _FORCE_BUILD_CACHE_CLEANUP: "true"  # Add this line for cache invalidation

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_GCR_HOSTNAME/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA'
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args:
      - run
      - deploy
      - $_SERVICE_NAME
      - '--image'
      - '$_GCR_HOSTNAME/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA'
      - '--region'
      - $_DEPLOY_REGION
      - '--platform'
      - $_PLATFORM
    entrypoint: gcloud
timeout: 1200s
images:
  - '$_GCR_HOSTNAME/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA'
